# Generated by Django 4.2.8 on 2024-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments_remove_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="currency",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="валюта"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="price_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="оплата"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="продукт"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="сессия"
            ),
        ),
    ]
