# Generated by Django 4.2.8 on 2024-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="null",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="null",
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Добавьте описание к курсу",
                verbose_name="описание",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=1100, null=True, verbose_name="цена"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Добавьте описание к уроку",
                verbose_name="описание",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=1100, null=True, verbose_name="цена"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lms/courses/previews",
                verbose_name="превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(
                help_text="Укажите ссылку на видео", verbose_name="Ссылка на видео"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lms/lessons/previews",
                verbose_name="превью",
            ),
        ),
    ]
