# Generated by Django 4.2.8 on 2024-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_alter_lesson_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="date_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата обновления"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_mailing",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="статус рассылки"
            ),
        ),
    ]
